"use client";

import Button from "./Button";
import Select from "./Select";

const REASONS = {
  loading: "Wait for the connection to load.", active_turns: "Wait for active browser turns to finish.", viewer_waiting: "Finish or end the private browser session before connecting Chrome.", viewer_open: "Close the private viewer before connecting Chrome.", draining: "Wait for the runtime to finish draining.", probing: "Wait for session verification to finish.", insecure_origin: "Open the dashboard over HTTPS (or loopback development).", unsaved_changes: "Save connection details and preferences before preparing a target.", profile_mismatch: "Save the selected profile before preparing a target.", expired: "The prepared target expired. Prepare a new connection explicitly.", consumed: "This attempt was consumed or its result is unknown. Verify the saved session before another attempt.",
};
export default function ChatGPTWebConnectionTab({ profile, loaded, busy, disabled, sessionDisabled, waiting, needsLogin, signInMethod, onMethodChange, openBrowser, endBrowser, verifySession, assistantOpen, importMode, changeImportMode, assistantReason, secureImportOrigin, directTarget, targetConsumed, targetElement, fileInput, onFileChange, connectionName, profileId, fileSelected, pastedSession, onPasteChange, importSession, prepareConnection, canPrepare, clipboardNotice, copyExtensionsAddress, connectionDetails, profiles, selectedProfileId, onProfileSelected }) {
  const ready = profile?.state === "ready" && profile.models.length > 0;
  return <div className="space-y-4">
    {ready ? <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-surface-2 p-4"><div><p className="font-medium">ChatGPT account session verified</p><p className="text-sm text-text-muted">{profile.models.length} verified models · {connectionName}</p></div><Button variant="secondary" disabled={disabled} onClick={openBrowser}>Open browser</Button></div> : (needsLogin || waiting) && (signInMethod === "browser" || waiting) ? <Button disabled={disabled || (!profile && !waiting) || (needsLogin && profile?.activeTurns > 0)} loading={busy === "Start login" || busy === "View browser"} onClick={openBrowser}>{waiting ? "Continue sign-in" : "Sign in"}</Button> : null}
    {!waiting && <Button variant="secondary" disabled={sessionDisabled} loading={busy === "Use Saved Session"} onClick={verifySession}>Verify saved session</Button>}
    {waiting && <Button variant="secondary" disabled={!!busy} onClick={endBrowser}>End private browser session</Button>}
    <details className="space-y-3"><summary className="cursor-pointer text-sm text-brand-500">Change sign-in method</summary><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!!busy} onClick={() => onMethodChange("extension")}>Chrome extension</Button><Button variant="secondary" disabled={!!busy} onClick={() => onMethodChange("browser")}>Private browser</Button></div></details>
    {assistantOpen && <section aria-label="Connect ChatGPT session" data-9router-chatgpt-session-assistant={JSON.stringify({ version: 1, reason: assistantReason })} className="min-w-0 space-y-3 rounded-lg border border-border p-4">
      <p className="text-xs text-amber-500">Session cookies are credentials. Connect only to your trusted dashboard; never send them to support.</p>
      <details><summary className="cursor-pointer text-xs text-text-muted">Credential handling details</summary><p className="mt-2 text-xs text-text-muted">Only the same ChatGPT account can be imported into an existing connection. Paste and file selection alone send nothing. Delete exported files and clear credential clipboard history after use.</p></details>
      <div ref={targetElement} data-9router-chatgpt-session-target={directTarget ? JSON.stringify(directTarget) : undefined} data-9router-chatgpt-session-consumed={directTarget && targetConsumed ? "true" : undefined} className="min-w-0 space-y-3">
        <input ref={fileInput} type="file" accept=".json,application/json" aria-label="Chrome session file" data-9router-chatgpt-session-file="" hidden disabled={sessionDisabled || !secureImportOrigin} onChange={onFileChange} />
        {importMode === "extension" && <>
          <ol className="list-decimal space-y-2 pl-5 text-sm"><li>Install the Chrome helper.</li><li>Open the helper on <strong>this dashboard tab</strong>, not on chatgpt.com.</li><li>Confirm the server and connection, then click Connect to this 9Router.</li></ol>
          <details className="space-y-2 rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm font-medium">Install or update helper</summary><a href="/downloads/chatgpt-web-session-export.zip" download="chatgpt-web-session-export.zip" className="inline-block text-sm text-brand-500 underline">Download Chrome helper</a><ol className="list-decimal space-y-2 pl-5 text-xs text-text-muted"><li>Extract the ZIP. For updates, replace the extracted helper and reload it.</li><li>Open <code>chrome://extensions</code>. <Button size="sm" variant="secondary" onClick={copyExtensionsAddress}>Copy address</Button></li><li>Enable Developer mode → Load unpacked → select the folder containing manifest.json.</li><li>Sign in at <a href="https://chatgpt.com" target="_blank" rel="noopener noreferrer" className="text-brand-500 underline">chatgpt.com</a> in the same Chrome profile, then return here. Open the helper icon or press Alt+Shift+9.</li></ol><p className="text-xs text-text-muted">Desktop Chrome only. Installation is not automatically detected. Other browsers and mobile can use the private browser or manual transfer.</p>{clipboardNotice && <p role="status" className="text-xs">{clipboardNotice}</p>}</details>
          <div className="break-all rounded-lg bg-surface-2 p-3 text-xs"><p>Server: <strong>{typeof window !== "undefined" ? window.location.origin : ""}</strong></p><p>Connection: <strong>{connectionName}</strong></p><details><summary className="cursor-pointer">Target details</summary><p>Profile: {profileId}</p>{directTarget && <p>Expires: {new Date(directTarget.expiresAt).toLocaleTimeString()}</p>}</details></div>
          <p role="status" className="text-sm text-text-muted">{REASONS[assistantReason] || (directTarget ? "Connection prepared for five minutes. Confirm the details in the Chrome helper. Opening it does not send cookies." : "No target is prepared. Prepare the saved idle connection.")}</p>
          {!directTarget && <Button disabled={!canPrepare} loading={!!busy} onClick={prepareConnection}>Prepare connection</Button>}
        </>}
        <details open={importMode !== "extension"} onToggle={event => { if (!event.currentTarget.open && importMode !== "extension") changeImportMode("extension"); }} className="space-y-3"><summary className="cursor-pointer text-sm">Manual import</summary><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={!!busy} onClick={() => changeImportMode("paste")}>Paste JSON</Button><Button variant="secondary" size="sm" disabled={!!busy} onClick={() => changeImportMode("file")}>Select file</Button></div>{importMode === "paste" && <><textarea aria-label="Session JSON" autoComplete="off" spellCheck={false} value={pastedSession} onChange={onPasteChange} disabled={sessionDisabled || !secureImportOrigin} rows={5} className="w-full rounded-lg border border-border bg-surface-2 p-3 font-mono text-xs" /><Button disabled={sessionDisabled || !secureImportOrigin || !pastedSession.trim()} loading={!!busy} onClick={() => importSession("paste")}>Import pasted session</Button></>}{importMode === "file" && <><Button variant="secondary" disabled={sessionDisabled || !secureImportOrigin} onClick={() => fileInput.current?.click()}>Choose session file</Button>{fileSelected && <p className="break-all text-xs">{fileSelected.name} · {fileSelected.size.toLocaleString()} bytes</p>}<Button disabled={sessionDisabled || !secureImportOrigin || !fileSelected} loading={!!busy} onClick={() => importSession("file")}>Import selected session</Button></>}</details>
      </div>
    </section>}
    <details className="space-y-3"><summary className="cursor-pointer text-sm">Connection details</summary>{connectionDetails}<Select label="Existing profiles" value={selectedProfileId} options={profiles.map(item => ({ value: item.profileId, label: `${item.profileId} — ${item.state.replaceAll("_", " ")}` }))} onChange={event => onProfileSelected(event.target.value)} disabled={!!busy} hint="This changes the connection draft only. Shared profiles share settings and the five-turn limit." /></details>
    {loaded && !profile && <p className="text-sm text-amber-500">The saved runtime profile is unavailable. Contact the operator; no replacement is created silently.</p>}
  </div>;
}
