"use client";

import Button from "./Button";
export default function ChatGPTWebDiagnosticsTab({ profile, harness, lease, disabled, sessionDisabled, busy, refresh, restart, verifyConnector, modelTest, endLogin }) {
  return <div className="space-y-4">
    <Button variant="secondary" disabled={!!busy} onClick={refresh}>Refresh diagnostics</Button>
    {profile && <><div className="space-y-1 rounded-lg bg-surface-2 p-3 text-sm"><p>State: <strong>{profile.state.replaceAll("_", " ")}</strong></p><p>Active browser turns: {profile.activeTurns} / {profile.maxConcurrency || 5}</p><p>Settings revision: {profile.revision} · Mode: {profile.settings.mode}</p><p>Connector: {profile.connectorReady ? "verified" : "not verified"}</p>{profile.lastError && <p className="text-amber-500">{profile.lastError.message}</p>}</div>
    <div className="space-y-2"><h3 className="text-sm font-medium">Verified models and reasoning efforts</h3>{profile.models.length ? <ul className="space-y-2 text-sm">{profile.models.map(model => <li key={model.id} className="rounded-lg bg-surface-2 p-3"><p>{model.display_name}{model.legacy ? " (legacy)" : ""}</p><p className="break-all text-xs text-text-muted">{model.id} · Efforts: {model.supported_reasoning_levels.join(", ")} · Default: {model.default_reasoning_level || "unknown"}{model.context_window ? ` · Context: ${model.context_window.toLocaleString()}` : ""}</p></li>)}</ul> : <p className="text-sm text-text-muted">No verified models. Verify the signed-in session in Connection.</p>}</div>
    <Button variant="secondary" disabled={disabled} loading={busy === "Restart browser"} onClick={restart}>Restart browser</Button></>}
    {harness && <div className="space-y-2 rounded-lg border border-border p-3 text-sm"><h3 className="font-medium">Harness checks</h3><p>Provisioning: {harness.source} · Config revision: {harness.configRevision}</p><p>Build compatibility: {harness.buildCompatible ? "passed" : "not passed"}</p><p>Tunnel: {harness.tunnelState} · Connector: {harness.connectorState}</p>{harness.lastError && <p className="text-amber-500">{harness.lastError.message}</p>}<p className="text-xs text-text-muted">Verify connector is zero-Send: it does not send a model prompt and does not prove tool execution on your client.</p><Button variant="secondary" disabled={sessionDisabled || harness.tunnelState !== "ready"} loading={busy === "Verify connector"} onClick={verifyConnector}>Verify connector (zero-Send)</Button></div>}
    {lease && <div className="space-y-2 text-sm"><p>Private browser: {lease.state} · Expires: {new Date(lease.expiresAt).toLocaleString()}</p>{lease.state === "waiting" && <Button variant="secondary" disabled={!!busy} onClick={endLogin}>End private browser session</Button>}</div>}
    <details className="space-y-3"><summary className="cursor-pointer text-sm">Model test (sends a real prompt)</summary><p className="text-xs text-text-muted">Runs only after clicking below. Connector readiness and client tool execution are separate checks.</p><Button variant="secondary" disabled={sessionDisabled} loading={busy === "Browser smoke"} onClick={modelTest}>Send one model test prompt</Button></details>
  </div>;
}
