import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstatSync, readFileSync } from "node:fs";
import { join } from "node:path";

const manifest = JSON.parse(readFileSync(new URL("../image-build-manifest.json", import.meta.url), "utf8"));
assert.equal(process.platform, "linux", "Private Chrome requires native Linux");
const arch = process.arch === "x64" ? "amd64" : process.arch;
assert(["amd64", "arm64"].includes(arch), "Unsupported Chrome architecture");
const browser = manifest.browser;
const asset = browser.platforms[arch];
assert.equal(process.env.CGW_CHROMIUM_EXECUTABLE, join(browser.installRoot, "chrome"), "Unexpected browser mount path");
const directory = lstatSync(browser.installRoot);
assert(directory.isDirectory() && !directory.isSymbolicLink() && !(directory.mode & 0o022), "Unsafe browser mount");
const proofPath = join(browser.installRoot, ".cgw-chrome.json");
assert(lstatSync(proofPath).isFile(), "Missing regular browser provenance");
const proof = JSON.parse(readFileSync(proofPath, "utf8"));
assert.equal(proof.version, browser.version);
assert.equal(proof.architecture, arch);
assert.equal(proof.archiveSha256, asset.sha256);
assert.equal(proof.binarySha256, asset.binarySha256);
const binaryPath = join(browser.installRoot, "chrome");
const file = lstatSync(binaryPath);
assert(file.isFile() && !(file.mode & 0o022) && (file.mode & 0o111), "Unsafe browser executable");
const binary = readFileSync(binaryPath);
assert.equal(binary.subarray(0, 6).toString("hex"), "7f454c460201", "Native ELF64 Chrome required");
assert.equal(binary.readUInt16LE(18), arch === "amd64" ? 62 : 183, "Wrong Chrome machine architecture");
assert.equal(createHash("sha256").update(binary).digest("hex"), asset.binarySha256, "Chrome binary checksum changed");
console.info(JSON.stringify({ gate: "private-browser-identity", architecture: arch, version: browser.version }));
