import { afterEach, expect, it } from "vitest";
import { createServer } from "node:http";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { getChatGptWebCatalog, invalidateChatGptWebCatalog } from "../../open-sse/services/chatgptWebRuntimeClient.js";
const cleanup = [];
afterEach(async () => { invalidateChatGptWebCatalog(); while (cleanup.length) await cleanup.pop()(); });
it("duplicate DB connections share one profile fetch and one cancelled waiter cannot abort other waiters", async () => {
  const root = await mkdtemp(join(tmpdir(), "cgw-single-flight-")); const secret = join(root, "secret"); await writeFile(secret, "synthetic-secret".repeat(4));
  const oldUrl = process.env.CHATGPT_WEB_RUNTIME_URL, oldSecret = process.env.CHATGPT_WEB_RUNTIME_TOKEN_FILE;
  cleanup.push(async () => { if (oldUrl === undefined) delete process.env.CHATGPT_WEB_RUNTIME_URL; else process.env.CHATGPT_WEB_RUNTIME_URL = oldUrl; if (oldSecret === undefined) delete process.env.CHATGPT_WEB_RUNTIME_TOKEN_FILE; else process.env.CHATGPT_WEB_RUNTIME_TOKEN_FILE = oldSecret; await rm(root, { recursive: true, force: true }); });
  let requests = 0, release;
  const observed = new Promise(resolve => { release = resolve; });
  const server = createServer((_request, response) => { requests++; release(); setTimeout(() => { response.setHeader("content-type", "application/json"); response.end(JSON.stringify({ protocolVersion: 1, profile_id: "fixture", profile_epoch: "epoch", catalog_revision: "revision", checked_at: new Date().toISOString(), max_concurrency: 5, models: [{ id: "chatgpt-web/gpt-5.6-sol", supported_reasoning_levels: ["high"], default_reasoning_level: "high", legacy: false, context_window: 90000, auto_compact_token_limit: 80000, capabilities: { native_responses: true } }] })); }, 30); });
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve)); cleanup.push(() => new Promise(resolve => { server.closeAllConnections(); server.close(resolve); }));
  process.env.CHATGPT_WEB_RUNTIME_URL = `http://127.0.0.1:${server.address().port}`; process.env.CHATGPT_WEB_RUNTIME_TOKEN_FILE = secret;
  const controller = new AbortController();
  const cancelled = getChatGptWebCatalog({ id: "one", providerSpecificData: { profileId: "fixture" } }, { signal: controller.signal }).catch(error => error.name);
  const surviving = getChatGptWebCatalog({ id: "two", providerSpecificData: { profileId: "fixture" } });
  await observed; controller.abort();
  expect(await cancelled).toBe("AbortError"); expect((await surviving).models[0].id).toBe("chatgpt-web/gpt-5.6-sol"); expect(requests).toBe(1);
});
